// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package client;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ClientMessage.messageTypes messageType = 1;</code>
     */
    int getMessageTypeValue();
    /**
     * <code>.ClientMessage.messageTypes messageType = 1;</code>
     */
    Message.ClientMessage.messageTypes getMessageType();

    /**
     * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
     */
    int getGroupActionTypeValue();
    /**
     * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
     */
    Message.ClientMessage.groupActionTypes getGroupActionType();

    /**
     * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
     */
    int getAuthorizationTypeValue();
    /**
     * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
     */
    Message.ClientMessage.authorizationTypes getAuthorizationType();

    /**
     * <code>string login = 4;</code>
     */
    java.lang.String getLogin();
    /**
     * <code>string login = 4;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>string password = 5;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 5;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string groupName = 6;</code>
     */
    java.lang.String getGroupName();
    /**
     * <code>string groupName = 6;</code>
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    /**
     * <code>string userName = 7;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 7;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string messageContent = 8;</code>
     */
    java.lang.String getMessageContent();
    /**
     * <code>string messageContent = 8;</code>
     */
    com.google.protobuf.ByteString
        getMessageContentBytes();

    /**
     * <code>.ClientMessage.replyStatus reply = 9;</code>
     */
    int getReplyValue();
    /**
     * <code>.ClientMessage.replyStatus reply = 9;</code>
     */
    Message.ClientMessage.replyStatus getReply();

    /**
     * <code>string replyContent = 10;</code>
     */
    java.lang.String getReplyContent();
    /**
     * <code>string replyContent = 10;</code>
     */
    com.google.protobuf.ByteString
        getReplyContentBytes();

    /**
     * <code>repeated string groups = 11;</code>
     */
    java.util.List<java.lang.String>
        getGroupsList();
    /**
     * <code>repeated string groups = 11;</code>
     */
    int getGroupsCount();
    /**
     * <code>repeated string groups = 11;</code>
     */
    java.lang.String getGroups(int index);
    /**
     * <code>repeated string groups = 11;</code>
     */
    com.google.protobuf.ByteString
        getGroupsBytes(int index);
  }
  /**
   * Protobuf type {@code ClientMessage}
   */
  public  static final class ClientMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientMessage)
      ClientMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientMessage() {
      messageType_ = 0;
      groupActionType_ = 0;
      authorizationType_ = 0;
      login_ = "";
      password_ = "";
      groupName_ = "";
      userName_ = "";
      messageContent_ = "";
      reply_ = 0;
      replyContent_ = "";
      groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              groupActionType_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              authorizationType_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              login_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              groupName_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              messageContent_ = s;
              break;
            }
            case 72: {
              int rawValue = input.readEnum();

              reply_ = rawValue;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              replyContent_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000400) != 0)) {
                groups_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000400;
              }
              groups_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000400) != 0)) {
          groups_ = groups_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_ClientMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.ClientMessage.class, Message.ClientMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code ClientMessage.messageTypes}
     */
    public enum messageTypes
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOMESSAGETYPE = 0;</code>
       */
      NOMESSAGETYPE(0),
      /**
       * <code>AUTHORIZATION = 1;</code>
       */
      AUTHORIZATION(1),
      /**
       * <code>GROUP = 2;</code>
       */
      GROUP(2),
      /**
       * <code>REPLY = 3;</code>
       */
      REPLY(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NOMESSAGETYPE = 0;</code>
       */
      public static final int NOMESSAGETYPE_VALUE = 0;
      /**
       * <code>AUTHORIZATION = 1;</code>
       */
      public static final int AUTHORIZATION_VALUE = 1;
      /**
       * <code>GROUP = 2;</code>
       */
      public static final int GROUP_VALUE = 2;
      /**
       * <code>REPLY = 3;</code>
       */
      public static final int REPLY_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static messageTypes valueOf(int value) {
        return forNumber(value);
      }

      public static messageTypes forNumber(int value) {
        switch (value) {
          case 0: return NOMESSAGETYPE;
          case 1: return AUTHORIZATION;
          case 2: return GROUP;
          case 3: return REPLY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<messageTypes>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          messageTypes> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<messageTypes>() {
              public messageTypes findValueByNumber(int number) {
                return messageTypes.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.ClientMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final messageTypes[] VALUES = values();

      public static messageTypes valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private messageTypes(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClientMessage.messageTypes)
    }

    /**
     * Protobuf enum {@code ClientMessage.groupActionTypes}
     */
    public enum groupActionTypes
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOGROUPTYPE = 0;</code>
       */
      NOGROUPTYPE(0),
      /**
       * <code>MESSAGE = 1;</code>
       */
      MESSAGE(1),
      /**
       * <code>CREATE = 2;</code>
       */
      CREATE(2),
      /**
       * <code>DELETE = 3;</code>
       */
      DELETE(3),
      /**
       * <code>REQUEST = 4;</code>
       */
      REQUEST(4),
      /**
       * <code>ACCEPT = 5;</code>
       */
      ACCEPT(5),
      /**
       * <code>DECLINE = 6;</code>
       */
      DECLINE(6),
      /**
       * <code>LEAVE = 7;</code>
       */
      LEAVE(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NOGROUPTYPE = 0;</code>
       */
      public static final int NOGROUPTYPE_VALUE = 0;
      /**
       * <code>MESSAGE = 1;</code>
       */
      public static final int MESSAGE_VALUE = 1;
      /**
       * <code>CREATE = 2;</code>
       */
      public static final int CREATE_VALUE = 2;
      /**
       * <code>DELETE = 3;</code>
       */
      public static final int DELETE_VALUE = 3;
      /**
       * <code>REQUEST = 4;</code>
       */
      public static final int REQUEST_VALUE = 4;
      /**
       * <code>ACCEPT = 5;</code>
       */
      public static final int ACCEPT_VALUE = 5;
      /**
       * <code>DECLINE = 6;</code>
       */
      public static final int DECLINE_VALUE = 6;
      /**
       * <code>LEAVE = 7;</code>
       */
      public static final int LEAVE_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static groupActionTypes valueOf(int value) {
        return forNumber(value);
      }

      public static groupActionTypes forNumber(int value) {
        switch (value) {
          case 0: return NOGROUPTYPE;
          case 1: return MESSAGE;
          case 2: return CREATE;
          case 3: return DELETE;
          case 4: return REQUEST;
          case 5: return ACCEPT;
          case 6: return DECLINE;
          case 7: return LEAVE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<groupActionTypes>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          groupActionTypes> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<groupActionTypes>() {
              public groupActionTypes findValueByNumber(int number) {
                return groupActionTypes.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.ClientMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final groupActionTypes[] VALUES = values();

      public static groupActionTypes valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private groupActionTypes(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClientMessage.groupActionTypes)
    }

    /**
     * Protobuf enum {@code ClientMessage.authorizationTypes}
     */
    public enum authorizationTypes
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOAUTHORIZATIONTYPE = 0;</code>
       */
      NOAUTHORIZATIONTYPE(0),
      /**
       * <code>LOG_IN = 1;</code>
       */
      LOG_IN(1),
      /**
       * <code>REGISTER = 2;</code>
       */
      REGISTER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NOAUTHORIZATIONTYPE = 0;</code>
       */
      public static final int NOAUTHORIZATIONTYPE_VALUE = 0;
      /**
       * <code>LOG_IN = 1;</code>
       */
      public static final int LOG_IN_VALUE = 1;
      /**
       * <code>REGISTER = 2;</code>
       */
      public static final int REGISTER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static authorizationTypes valueOf(int value) {
        return forNumber(value);
      }

      public static authorizationTypes forNumber(int value) {
        switch (value) {
          case 0: return NOAUTHORIZATIONTYPE;
          case 1: return LOG_IN;
          case 2: return REGISTER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<authorizationTypes>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          authorizationTypes> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<authorizationTypes>() {
              public authorizationTypes findValueByNumber(int number) {
                return authorizationTypes.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.ClientMessage.getDescriptor().getEnumTypes().get(2);
      }

      private static final authorizationTypes[] VALUES = values();

      public static authorizationTypes valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private authorizationTypes(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClientMessage.authorizationTypes)
    }

    /**
     * Protobuf enum {@code ClientMessage.replyStatus}
     */
    public enum replyStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOSTATUS = 0;</code>
       */
      NOSTATUS(0),
      /**
       * <code>POSITIVE = 1;</code>
       */
      POSITIVE(1),
      /**
       * <code>NEGATIVE = 2;</code>
       */
      NEGATIVE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NOSTATUS = 0;</code>
       */
      public static final int NOSTATUS_VALUE = 0;
      /**
       * <code>POSITIVE = 1;</code>
       */
      public static final int POSITIVE_VALUE = 1;
      /**
       * <code>NEGATIVE = 2;</code>
       */
      public static final int NEGATIVE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static replyStatus valueOf(int value) {
        return forNumber(value);
      }

      public static replyStatus forNumber(int value) {
        switch (value) {
          case 0: return NOSTATUS;
          case 1: return POSITIVE;
          case 2: return NEGATIVE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<replyStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          replyStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<replyStatus>() {
              public replyStatus findValueByNumber(int number) {
                return replyStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.ClientMessage.getDescriptor().getEnumTypes().get(3);
      }

      private static final replyStatus[] VALUES = values();

      public static replyStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private replyStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ClientMessage.replyStatus)
    }

    private int bitField0_;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>.ClientMessage.messageTypes messageType = 1;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.ClientMessage.messageTypes messageType = 1;</code>
     */
    public Message.ClientMessage.messageTypes getMessageType() {
      @SuppressWarnings("deprecation")
      Message.ClientMessage.messageTypes result = Message.ClientMessage.messageTypes.valueOf(messageType_);
      return result == null ? Message.ClientMessage.messageTypes.UNRECOGNIZED : result;
    }

    public static final int GROUPACTIONTYPE_FIELD_NUMBER = 2;
    private int groupActionType_;
    /**
     * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
     */
    public int getGroupActionTypeValue() {
      return groupActionType_;
    }
    /**
     * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
     */
    public Message.ClientMessage.groupActionTypes getGroupActionType() {
      @SuppressWarnings("deprecation")
      Message.ClientMessage.groupActionTypes result = Message.ClientMessage.groupActionTypes.valueOf(groupActionType_);
      return result == null ? Message.ClientMessage.groupActionTypes.UNRECOGNIZED : result;
    }

    public static final int AUTHORIZATIONTYPE_FIELD_NUMBER = 3;
    private int authorizationType_;
    /**
     * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
     */
    public int getAuthorizationTypeValue() {
      return authorizationType_;
    }
    /**
     * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
     */
    public Message.ClientMessage.authorizationTypes getAuthorizationType() {
      @SuppressWarnings("deprecation")
      Message.ClientMessage.authorizationTypes result = Message.ClientMessage.authorizationTypes.valueOf(authorizationType_);
      return result == null ? Message.ClientMessage.authorizationTypes.UNRECOGNIZED : result;
    }

    public static final int LOGIN_FIELD_NUMBER = 4;
    private volatile java.lang.Object login_;
    /**
     * <code>string login = 4;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      }
    }
    /**
     * <code>string login = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 5;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 5;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object groupName_;
    /**
     * <code>string groupName = 6;</code>
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      }
    }
    /**
     * <code>string groupName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object userName_;
    /**
     * <code>string userName = 7;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGECONTENT_FIELD_NUMBER = 8;
    private volatile java.lang.Object messageContent_;
    /**
     * <code>string messageContent = 8;</code>
     */
    public java.lang.String getMessageContent() {
      java.lang.Object ref = messageContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageContent_ = s;
        return s;
      }
    }
    /**
     * <code>string messageContent = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMessageContentBytes() {
      java.lang.Object ref = messageContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPLY_FIELD_NUMBER = 9;
    private int reply_;
    /**
     * <code>.ClientMessage.replyStatus reply = 9;</code>
     */
    public int getReplyValue() {
      return reply_;
    }
    /**
     * <code>.ClientMessage.replyStatus reply = 9;</code>
     */
    public Message.ClientMessage.replyStatus getReply() {
      @SuppressWarnings("deprecation")
      Message.ClientMessage.replyStatus result = Message.ClientMessage.replyStatus.valueOf(reply_);
      return result == null ? Message.ClientMessage.replyStatus.UNRECOGNIZED : result;
    }

    public static final int REPLYCONTENT_FIELD_NUMBER = 10;
    private volatile java.lang.Object replyContent_;
    /**
     * <code>string replyContent = 10;</code>
     */
    public java.lang.String getReplyContent() {
      java.lang.Object ref = replyContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyContent_ = s;
        return s;
      }
    }
    /**
     * <code>string replyContent = 10;</code>
     */
    public com.google.protobuf.ByteString
        getReplyContentBytes() {
      java.lang.Object ref = replyContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPS_FIELD_NUMBER = 11;
    private com.google.protobuf.LazyStringList groups_;
    /**
     * <code>repeated string groups = 11;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getGroupsList() {
      return groups_;
    }
    /**
     * <code>repeated string groups = 11;</code>
     */
    public int getGroupsCount() {
      return groups_.size();
    }
    /**
     * <code>repeated string groups = 11;</code>
     */
    public java.lang.String getGroups(int index) {
      return groups_.get(index);
    }
    /**
     * <code>repeated string groups = 11;</code>
     */
    public com.google.protobuf.ByteString
        getGroupsBytes(int index) {
      return groups_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != Message.ClientMessage.messageTypes.NOMESSAGETYPE.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (groupActionType_ != Message.ClientMessage.groupActionTypes.NOGROUPTYPE.getNumber()) {
        output.writeEnum(2, groupActionType_);
      }
      if (authorizationType_ != Message.ClientMessage.authorizationTypes.NOAUTHORIZATIONTYPE.getNumber()) {
        output.writeEnum(3, authorizationType_);
      }
      if (!getLoginBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, login_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, password_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, groupName_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userName_);
      }
      if (!getMessageContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, messageContent_);
      }
      if (reply_ != Message.ClientMessage.replyStatus.NOSTATUS.getNumber()) {
        output.writeEnum(9, reply_);
      }
      if (!getReplyContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, replyContent_);
      }
      for (int i = 0; i < groups_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, groups_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != Message.ClientMessage.messageTypes.NOMESSAGETYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (groupActionType_ != Message.ClientMessage.groupActionTypes.NOGROUPTYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, groupActionType_);
      }
      if (authorizationType_ != Message.ClientMessage.authorizationTypes.NOAUTHORIZATIONTYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, authorizationType_);
      }
      if (!getLoginBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, login_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, password_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, groupName_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userName_);
      }
      if (!getMessageContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, messageContent_);
      }
      if (reply_ != Message.ClientMessage.replyStatus.NOSTATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, reply_);
      }
      if (!getReplyContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, replyContent_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < groups_.size(); i++) {
          dataSize += computeStringSizeNoTag(groups_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getGroupsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message.ClientMessage)) {
        return super.equals(obj);
      }
      Message.ClientMessage other = (Message.ClientMessage) obj;

      if (messageType_ != other.messageType_) return false;
      if (groupActionType_ != other.groupActionType_) return false;
      if (authorizationType_ != other.authorizationType_) return false;
      if (!getLogin()
          .equals(other.getLogin())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getGroupName()
          .equals(other.getGroupName())) return false;
      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getMessageContent()
          .equals(other.getMessageContent())) return false;
      if (reply_ != other.reply_) return false;
      if (!getReplyContent()
          .equals(other.getReplyContent())) return false;
      if (!getGroupsList()
          .equals(other.getGroupsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + GROUPACTIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + groupActionType_;
      hash = (37 * hash) + AUTHORIZATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + authorizationType_;
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGroupName().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + MESSAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMessageContent().hashCode();
      hash = (37 * hash) + REPLY_FIELD_NUMBER;
      hash = (53 * hash) + reply_;
      hash = (37 * hash) + REPLYCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getReplyContent().hashCode();
      if (getGroupsCount() > 0) {
        hash = (37 * hash) + GROUPS_FIELD_NUMBER;
        hash = (53 * hash) + getGroupsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message.ClientMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.ClientMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message.ClientMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientMessage)
        Message.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_ClientMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_ClientMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.ClientMessage.class, Message.ClientMessage.Builder.class);
      }

      // Construct using Message.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        groupActionType_ = 0;

        authorizationType_ = 0;

        login_ = "";

        password_ = "";

        groupName_ = "";

        userName_ = "";

        messageContent_ = "";

        reply_ = 0;

        replyContent_ = "";

        groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_ClientMessage_descriptor;
      }

      @java.lang.Override
      public Message.ClientMessage getDefaultInstanceForType() {
        return Message.ClientMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Message.ClientMessage build() {
        Message.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Message.ClientMessage buildPartial() {
        Message.ClientMessage result = new Message.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.messageType_ = messageType_;
        result.groupActionType_ = groupActionType_;
        result.authorizationType_ = authorizationType_;
        result.login_ = login_;
        result.password_ = password_;
        result.groupName_ = groupName_;
        result.userName_ = userName_;
        result.messageContent_ = messageContent_;
        result.reply_ = reply_;
        result.replyContent_ = replyContent_;
        if (((bitField0_ & 0x00000400) != 0)) {
          groups_ = groups_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000400);
        }
        result.groups_ = groups_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.ClientMessage) {
          return mergeFrom((Message.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.ClientMessage other) {
        if (other == Message.ClientMessage.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.groupActionType_ != 0) {
          setGroupActionTypeValue(other.getGroupActionTypeValue());
        }
        if (other.authorizationType_ != 0) {
          setAuthorizationTypeValue(other.getAuthorizationTypeValue());
        }
        if (!other.getLogin().isEmpty()) {
          login_ = other.login_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getGroupName().isEmpty()) {
          groupName_ = other.groupName_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getMessageContent().isEmpty()) {
          messageContent_ = other.messageContent_;
          onChanged();
        }
        if (other.reply_ != 0) {
          setReplyValue(other.getReplyValue());
        }
        if (!other.getReplyContent().isEmpty()) {
          replyContent_ = other.replyContent_;
          onChanged();
        }
        if (!other.groups_.isEmpty()) {
          if (groups_.isEmpty()) {
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000400);
          } else {
            ensureGroupsIsMutable();
            groups_.addAll(other.groups_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.ClientMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.ClientMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int messageType_ = 0;
      /**
       * <code>.ClientMessage.messageTypes messageType = 1;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.ClientMessage.messageTypes messageType = 1;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.messageTypes messageType = 1;</code>
       */
      public Message.ClientMessage.messageTypes getMessageType() {
        @SuppressWarnings("deprecation")
        Message.ClientMessage.messageTypes result = Message.ClientMessage.messageTypes.valueOf(messageType_);
        return result == null ? Message.ClientMessage.messageTypes.UNRECOGNIZED : result;
      }
      /**
       * <code>.ClientMessage.messageTypes messageType = 1;</code>
       */
      public Builder setMessageType(Message.ClientMessage.messageTypes value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.messageTypes messageType = 1;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int groupActionType_ = 0;
      /**
       * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
       */
      public int getGroupActionTypeValue() {
        return groupActionType_;
      }
      /**
       * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
       */
      public Builder setGroupActionTypeValue(int value) {
        groupActionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
       */
      public Message.ClientMessage.groupActionTypes getGroupActionType() {
        @SuppressWarnings("deprecation")
        Message.ClientMessage.groupActionTypes result = Message.ClientMessage.groupActionTypes.valueOf(groupActionType_);
        return result == null ? Message.ClientMessage.groupActionTypes.UNRECOGNIZED : result;
      }
      /**
       * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
       */
      public Builder setGroupActionType(Message.ClientMessage.groupActionTypes value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        groupActionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.groupActionTypes groupActionType = 2;</code>
       */
      public Builder clearGroupActionType() {
        
        groupActionType_ = 0;
        onChanged();
        return this;
      }

      private int authorizationType_ = 0;
      /**
       * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
       */
      public int getAuthorizationTypeValue() {
        return authorizationType_;
      }
      /**
       * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
       */
      public Builder setAuthorizationTypeValue(int value) {
        authorizationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
       */
      public Message.ClientMessage.authorizationTypes getAuthorizationType() {
        @SuppressWarnings("deprecation")
        Message.ClientMessage.authorizationTypes result = Message.ClientMessage.authorizationTypes.valueOf(authorizationType_);
        return result == null ? Message.ClientMessage.authorizationTypes.UNRECOGNIZED : result;
      }
      /**
       * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
       */
      public Builder setAuthorizationType(Message.ClientMessage.authorizationTypes value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        authorizationType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.authorizationTypes authorizationType = 3;</code>
       */
      public Builder clearAuthorizationType() {
        
        authorizationType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object login_ = "";
      /**
       * <code>string login = 4;</code>
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login = 4;</code>
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string login = 4;</code>
       */
      public Builder clearLogin() {
        
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>string login = 4;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        login_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 5;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 5;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 5;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 5;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object groupName_ = "";
      /**
       * <code>string groupName = 6;</code>
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string groupName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string groupName = 6;</code>
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string groupName = 6;</code>
       */
      public Builder clearGroupName() {
        
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      /**
       * <code>string groupName = 6;</code>
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 7;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 7;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 7;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 7;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageContent_ = "";
      /**
       * <code>string messageContent = 8;</code>
       */
      public java.lang.String getMessageContent() {
        java.lang.Object ref = messageContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageContent = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMessageContentBytes() {
        java.lang.Object ref = messageContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageContent = 8;</code>
       */
      public Builder setMessageContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageContent = 8;</code>
       */
      public Builder clearMessageContent() {
        
        messageContent_ = getDefaultInstance().getMessageContent();
        onChanged();
        return this;
      }
      /**
       * <code>string messageContent = 8;</code>
       */
      public Builder setMessageContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageContent_ = value;
        onChanged();
        return this;
      }

      private int reply_ = 0;
      /**
       * <code>.ClientMessage.replyStatus reply = 9;</code>
       */
      public int getReplyValue() {
        return reply_;
      }
      /**
       * <code>.ClientMessage.replyStatus reply = 9;</code>
       */
      public Builder setReplyValue(int value) {
        reply_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.replyStatus reply = 9;</code>
       */
      public Message.ClientMessage.replyStatus getReply() {
        @SuppressWarnings("deprecation")
        Message.ClientMessage.replyStatus result = Message.ClientMessage.replyStatus.valueOf(reply_);
        return result == null ? Message.ClientMessage.replyStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.ClientMessage.replyStatus reply = 9;</code>
       */
      public Builder setReply(Message.ClientMessage.replyStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        reply_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ClientMessage.replyStatus reply = 9;</code>
       */
      public Builder clearReply() {
        
        reply_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object replyContent_ = "";
      /**
       * <code>string replyContent = 10;</code>
       */
      public java.lang.String getReplyContent() {
        java.lang.Object ref = replyContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          replyContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string replyContent = 10;</code>
       */
      public com.google.protobuf.ByteString
          getReplyContentBytes() {
        java.lang.Object ref = replyContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replyContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string replyContent = 10;</code>
       */
      public Builder setReplyContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        replyContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string replyContent = 10;</code>
       */
      public Builder clearReplyContent() {
        
        replyContent_ = getDefaultInstance().getReplyContent();
        onChanged();
        return this;
      }
      /**
       * <code>string replyContent = 10;</code>
       */
      public Builder setReplyContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        replyContent_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGroupsIsMutable() {
        if (!((bitField0_ & 0x00000400) != 0)) {
          groups_ = new com.google.protobuf.LazyStringArrayList(groups_);
          bitField0_ |= 0x00000400;
         }
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getGroupsList() {
        return groups_.getUnmodifiableView();
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public int getGroupsCount() {
        return groups_.size();
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public java.lang.String getGroups(int index) {
        return groups_.get(index);
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public com.google.protobuf.ByteString
          getGroupsBytes(int index) {
        return groups_.getByteString(index);
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public Builder setGroups(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupsIsMutable();
        groups_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public Builder addGroups(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public Builder addAllGroups(
          java.lang.Iterable<java.lang.String> values) {
        ensureGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groups_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public Builder clearGroups() {
        groups_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string groups = 11;</code>
       */
      public Builder addGroupsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientMessage)
    }

    // @@protoc_insertion_point(class_scope:ClientMessage)
    private static final Message.ClientMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message.ClientMessage();
    }

    public static Message.ClientMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientMessage>
        PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
      @java.lang.Override
      public ClientMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Message.ClientMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"\261\005\n\rClientMessage\0220\n\013mes" +
      "sageType\030\001 \001(\0162\033.ClientMessage.messageTy" +
      "pes\0228\n\017groupActionType\030\002 \001(\0162\037.ClientMes" +
      "sage.groupActionTypes\022<\n\021authorizationTy" +
      "pe\030\003 \001(\0162!.ClientMessage.authorizationTy" +
      "pes\022\r\n\005login\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022\021\n\t" +
      "groupName\030\006 \001(\t\022\020\n\010userName\030\007 \001(\t\022\026\n\016mes" +
      "sageContent\030\010 \001(\t\022)\n\005reply\030\t \001(\0162\032.Clien" +
      "tMessage.replyStatus\022\024\n\014replyContent\030\n \001" +
      "(\t\022\016\n\006groups\030\013 \003(\t\"J\n\014messageTypes\022\021\n\rNO" +
      "MESSAGETYPE\020\000\022\021\n\rAUTHORIZATION\020\001\022\t\n\005GROU" +
      "P\020\002\022\t\n\005REPLY\020\003\"y\n\020groupActionTypes\022\017\n\013NO" +
      "GROUPTYPE\020\000\022\013\n\007MESSAGE\020\001\022\n\n\006CREATE\020\002\022\n\n\006" +
      "DELETE\020\003\022\013\n\007REQUEST\020\004\022\n\n\006ACCEPT\020\005\022\013\n\007DEC" +
      "LINE\020\006\022\t\n\005LEAVE\020\007\"G\n\022authorizationTypes\022" +
      "\027\n\023NOAUTHORIZATIONTYPE\020\000\022\n\n\006LOG_IN\020\001\022\014\n\010" +
      "REGISTER\020\002\"7\n\013replyStatus\022\014\n\010NOSTATUS\020\000\022" +
      "\014\n\010POSITIVE\020\001\022\014\n\010NEGATIVE\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientMessage_descriptor,
        new java.lang.String[] { "MessageType", "GroupActionType", "AuthorizationType", "Login", "Password", "GroupName", "UserName", "MessageContent", "Reply", "ReplyContent", "Groups", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
